# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-07 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190306_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='down_count',
            field=models.IntegerField(default=0, verbose_name='踩数'),
        ),
    ]
